version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: telegram-postback-bot
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_WEBHOOK_URL=${TELEGRAM_WEBHOOK_URL}
      - PROPELLERADS_AID=${PROPELLERADS_AID}
      - PROPELLERADS_TID=${PROPELLERADS_TID}
      - PROPELLERADS_POSTBACK_URL=${PROPELLERADS_POSTBACK_URL}
    volumes:
      - ./logs:/app/logs
      - ./subid_map.json:/app/subid_map.json
    networks:
      - bot-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:alpine
    container_name: telegram-bot-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - telegram-bot
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge

volumes:
  logs:
  bot-data:


